INSERT INTO `person` (`address`, `first_name`, `gender`, `last_name`)
VALUES ('USA - NY - New York', 'Jeff', 'male', 'Bezos'),
       ('USA - CA - Los Angeles', 'Elon', 'male', 'Musk'),
       ('USA - CA - San Francisco', 'Mark', 'male', 'Zuckerberg'),
       ('USA - WA - Seattle', 'Bill', 'male', 'Gates'),
       ('France - IDF - Paris', 'Bernard', 'male', 'Arnault'),
       ('USA - CA - Palo Alto', 'Larry', 'male', 'Page'),
       ('USA - CA - Menlo Park', 'Sergey', 'male', 'Brin'),
       ('USA - WA - Seattle', 'Steve', 'male', 'Ballmer'),
       ('USA - NE - Omaha', 'Warren', 'male', 'Buffett'),
       ('USA - CA - San Francisco', 'Larry', 'male', 'Ellison'),
       ('China - SH - Shanghai', 'Jack', 'male', 'Ma'),
       ('India - DL - New Delhi', 'Mukesh', 'male', 'Ambani'),
       ('USA - NY - New York', 'Michael', 'male', 'Bloomberg'),
       ('Hong Kong - HK - Central', 'Li', 'male', 'Ka-shing'),
       ('USA - FL - Miami', 'Carl', 'male', 'Icahn'),
       ('Brazil - SP - São Paulo', 'Jorge', 'male', 'Paulo Lemann'),
       ('USA - CA - San Jose', 'Safra', 'female', 'Catz'),
       ('USA - CA - San Francisco', 'Dustin', 'male', 'Moskovitz'),
       ('USA - TX - Austin', 'Michael', 'male', 'Dell'),
       ('USA - CA - San Francisco', 'Evan', 'male', 'Spiegel'),
       ('USA - WA - Bellevue', 'Melinda', 'female', 'Gates'),
       ('USA - CA - Santa Monica', 'Sergey', 'male', 'Brin'),
       ('USA - NY - New York', 'Laurene', 'female', 'Powell Jobs'),
       ('USA - CA - Palo Alto', 'Reed', 'male', 'Hastings'),
       ('USA - TX - Houston', 'Tilman', 'male', 'Fertitta'),
       ('USA - NY - New York', 'James', 'male', 'Harris'),
       ('USA - FL - Naples', 'Ken', 'male', 'Griffin'),
       ('USA - CA - Santa Barbara', 'Patrick', 'male', 'Soon-Shiong'),
       ('USA - CA - Palo Alto', 'Sheryl', 'female', 'Sandberg'),
       ('China - BJ - Beijing', 'Pony', 'male', 'Ma'),
       ('USA - CA - Los Angeles', 'Kylie', 'female', 'Jenner'),
       ('USA - CA - Menlo Park', 'Peter', 'male', 'Thiel'),
       ('USA - NY - New York', 'Larry', 'male', 'Fink'),
       ('USA - TX - Austin', 'Kirk', 'male', 'Kirkland'),
       ('USA - FL - Miami', 'Paul', 'male', 'Hewson'),
       ('USA - CA - Cupertino', 'Tim', 'male', 'Cook'),
       ('USA - CA - Los Angeles', 'Gordon', 'male', 'Moore'),
       ('USA - NY - New York', 'Richard', 'male', 'Branson'),
       ('USA - TX - Dallas', 'Mark', 'male', 'Cuban'),
       ('USA - CA - Santa Clara', 'Vinod', 'male', 'Khosla'),
       ('USA - TX - Austin', 'Robert', 'male', 'Smith'),
       ('USA - CA - Palo Alto', 'Peter', 'male', 'Thiel'),
       ('USA - TX - Houston', 'Andrew', 'male', 'Beal'),
       ('USA - CA - Beverly Hills', 'Leonard', 'male', 'Lauder'),
       ('USA - NY - New York', 'Howard', 'male', 'Marks'),
       ('USA - CA - Palo Alto', 'John', 'male', 'Doerr'),
       ('USA - CA - Los Angeles', 'Anastasia', 'female', 'Soare'),
       ('USA - TX - Dallas', 'Edward', 'male', 'Bass'),
       ('USA - CA - Los Angeles', 'Jeffrey', 'male', 'Yass'),
       ('USA - CA - Santa Barbara', 'Evan', 'male', 'Spiegel'),
       ('USA - CA - Palo Alto', 'Rob', 'male', 'Lowe'),
       ('USA - CA - Palo Alto', 'Yoshikazu', 'male', 'Tamada'),
       ('USA - NY - New York', 'Donald', 'male', 'Trump'),
       ('USA - CA - Los Angeles', 'Shari', 'female', 'Redstone'),
       ('USA - NY - New York', 'Robert', 'male', 'F. Smith'),
       ('USA - TX - Austin', 'Michael', 'male', 'S. Dell'),
       ('USA - CA - Los Angeles', 'Rihanna', 'female', 'Fenty'),
       ('USA - CA - Los Angeles', 'Elliot', 'male', 'Tebele'),
       ('USA - NY - New York', 'Peter', 'male', 'Thiel'),
       ('USA - CA - Palo Alto', 'Michael', 'male', 'Kirkland'),
       ('USA - TX - Austin', 'Elaine', 'female', 'Chao'),
       ('USA - CA - Menlo Park', 'Steven', 'male', 'Miller'),
       ('USA - CA - Palo Alto', 'Michael', 'male', 'Levin'),
       ('USA - CA - San Francisco', 'David', 'male', 'Cohen'),
       ('USA - CA - Palo Alto', 'John', 'male', 'Doerr'),
       ('USA - CA - Palo Alto', 'Marc', 'male', 'Andreesen'),
       ('USA - CA - Los Angeles', 'David', 'male', 'Geffen'),
       ('USA - NY - New York', 'Laurene', 'female', 'Powell Jobs'),
       ('USA - TX - Dallas', 'James', 'male', 'Harris'),
       ('USA - CA - Los Angeles', 'Harlan', 'male', 'Crow'),
       ('USA - CA - Palo Alto', 'Jeff', 'male', 'Epstein'),
       ('USA - CA - Menlo Park', 'Kurt', 'male', 'Kiser'),
       ('USA - CA - Palo Alto', 'James', 'male', 'Harris'),
       ('USA - CA - San Francisco', 'Evan', 'male', 'Spiegel'),
       ('USA - CA - Menlo Park', 'Jennifer', 'female', 'Ainsworth'),
       ('USA - CA - Palo Alto', 'Martha', 'female', 'Stewart'),
       ('USA - CA - Palo Alto', 'Jack', 'male', 'Dorsey'),
       ('USA - TX - Houston', 'Alex', 'male', 'Schultz'),
       ('USA - CA - Palo Alto', 'Michelle', 'female', 'Zuckerberg'),
       ('USA - NY - New York', 'Alison', 'female', 'Epps'),
       ('USA - CA - San Francisco', 'Paul', 'male', 'Dudley'),
       ('USA - NY - New York', 'Fred', 'male', 'Smith'),
       ('USA - CA - Menlo Park', 'Ben', 'male', 'Horowitz'),
       ('USA - CA - Palo Alto', 'Evan', 'male', 'Spiegel'),
       ('USA - TX - Dallas', 'Lloyd', 'male', 'Blankfein'),
       ('USA - CA - Palo Alto', 'Vinod', 'male', 'Khosla'),
       ('USA - CA - San Francisco', 'Evan', 'male', 'Spiegel'),
       ('USA - CA - San Francisco', 'Richard', 'male', 'Miller'),
       ('USA - TX - Dallas', 'Jeff', 'male', 'Bezos'),
       ('USA - CA - Los Angeles', 'Bobby', 'male', 'Murphy'),
       ('USA - NY - New York', 'Chad', 'male', 'Harris'),
       ('USA - CA - San Francisco', 'Larry', 'male', 'Page'),
       ('USA - NY - New York', 'Drew', 'male', 'Houston'),
       ('USA - CA - San Francisco', 'Jessica', 'female', 'Alba'),
       ('USA - TX - Houston', 'Ben', 'male', 'Horowitz'),
       ('USA - NY - New York', 'Laurene', 'female', 'Powell Jobs'),
       ('USA - CA - San Francisco', 'Daniel', 'male', 'Kraft'),
       ('USA - TX - Houston', 'Dustin', 'male', 'Moskovitz'),
       ('USA - NY - New York', 'Michelle', 'female', 'Zuckerberg'),
       ('USA - CA - Palo Alto', 'Jack', 'male', 'Dorsey'),
       ('USA - CA - Palo Alto', 'Larry', 'male', 'Ellison'),
       ('USA - NY - New York', 'Amanda', 'female', 'Hsu'),
       ('USA - TX - Dallas', 'James', 'male', 'Harris'),
       ('USA - CA - Menlo Park', 'Laura', 'female', 'Chao'),
       ('USA - NY - New York', 'Warren', 'male', 'Buffett');